"""
Seller Authorization Manifest -- Phase 10

The seller-side complement to AP2 v0.2.0 Signed Mandates (Phase 9).

PROBLEM:
  HTTPS gives browser commerce a cryptographic trust signal: the padlock proves
  the server is operated by the named entity. Agentic and social commerce remove
  the browser. There is no padlock, no URL bar, no SSL certificate visible to the
  human buyer. A chat interface or social platform navigating to a seller on a
  human's behalf has no machine-readable signal to verify the seller is legitimate
  and the offer is genuine.

THIS MODULE:
  Seller Authorization Manifest: signed by the merchant's human operator before
  the selling agent goes live. States what the agent may sell, at what price
  ranges, with what discount limits. In production this is a LoginID biometric
  ceremony -- the same signing UX as the Intent Mandate on the buyer side.

  Signed Offer: generated by the seller agent for each quote. Signed against
  the manifest. The buyer agent or chat interface receives the signed offer and
  calls verify_signed_offer() to confirm: the merchant's human owner authorized
  this SKU at this price, and the agent signed this specific quote.

CLERK ENFORCEMENT ADVANCE:
  This is the first runtime enforcement gate in SupplyMind. Prior phases produced
  audit trails. This produces a verification failure at the transaction boundary,
  before the human is asked to confirm -- deviation from the manifest is caught
  when the quote is presented, not after money moves.

NOT AP2:
  AP2 governs buyer-side spending. No seller-side equivalent standard exists.
  This module borrows AP2's cryptographic pattern and applies it to the seller.
"""

import uuid
from datetime import datetime, timezone
from typing import Optional

from src.identity.keys import sign_document, verify_signature, public_key_to_hex

SELLER_MANIFESTS: dict[str, dict] = {}
SIGNED_OFFERS:   dict[str, dict] = {}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def create_seller_manifest(
    operator_id:    str,
    seller_agent_id: str,
    seller_dnsid:   str,
    authorized_skus: list[dict],
    private_key,
) -> dict:
    """
    Create a signed Seller Authorization Manifest.

    authorized_skus is a list of dicts, each with:
      sku:            str   -- the product SKU
      min_price_usd:  float -- lowest price the agent may quote
      max_price_usd:  float -- highest price the agent may quote
      max_discount_pct: float -- maximum bulk discount percentage allowed

    In production, private_key is held by a LoginID-managed hardware credential.
    The signing ceremony is identical to Intent Mandate creation (Phase 9):
    biometric gesture by the merchant operator authorizes the manifest.

    Returns the full manifest dict including proof field.
    """
    manifest_id = str(uuid.uuid4())
    manifest = {
        "schema":           "sam:seller-manifest:v0.1.0",
        "manifest_id":      manifest_id,
        "operator_id":      operator_id,
        "seller_agent_id":  seller_agent_id,
        "seller_dnsid":     seller_dnsid,
        "authorized_skus":  authorized_skus,
        "created_at":       _now(),
        "public_key_hex":   public_key_to_hex(private_key.public_key()),
    }
    manifest["proof"] = {
        "type":      "secp256k1-sha256",
        "created":   _now(),
        "signature": sign_document(manifest, private_key),
    }
    SELLER_MANIFESTS[manifest_id] = manifest
    return manifest


def create_signed_offer(
    manifest_id: str,
    sku:         str,
    quantity:    int,
    unit_price:  float,
    discount_pct: float,
    private_key,
    buyer_id:    Optional[str] = None,
) -> dict:
    """
    Create a signed offer for a specific quote.

    Validates the offer against the manifest before signing:
      - SKU must be in the manifest's authorized_skus list
      - unit_price must be within [min_price_usd, max_price_usd]
      - discount_pct must not exceed max_discount_pct

    Returns an error dict if constraints are violated.
    Returns the signed offer dict if valid.

    In production, private_key is the seller agent's secp256k1 key (Phase 7).
    """
    manifest = SELLER_MANIFESTS.get(manifest_id)
    if not manifest:
        return {"error": f"Seller Manifest {manifest_id} not found"}

    sku_rule = next((s for s in manifest["authorized_skus"] if s["sku"] == sku.upper()), None)
    if not sku_rule:
        return {"error": f"SKU {sku} not authorized in manifest {manifest_id}"}

    if unit_price < sku_rule["min_price_usd"]:
        return {"error": f"Unit price ${unit_price:.2f} below manifest minimum ${sku_rule['min_price_usd']:.2f}"}
    if unit_price > sku_rule["max_price_usd"]:
        return {"error": f"Unit price ${unit_price:.2f} above manifest maximum ${sku_rule['max_price_usd']:.2f}"}
    if discount_pct > sku_rule["max_discount_pct"]:
        return {"error": f"Discount {discount_pct:.1f}% exceeds manifest limit {sku_rule['max_discount_pct']:.1f}%"}

    offer_id = str(uuid.uuid4())
    total    = round(unit_price * (1 - discount_pct / 100) * quantity, 2)

    offer = {
        "schema":       "sam:signed-offer:v0.1.0",
        "offer_id":     offer_id,
        "manifest_id":  manifest_id,
        "sku":          sku.upper(),
        "quantity":     quantity,
        "unit_price":   unit_price,
        "discount_pct": discount_pct,
        "total_usd":    total,
        "buyer_id":     buyer_id,
        "created_at":   _now(),
        "public_key_hex": public_key_to_hex(private_key.public_key()),
    }
    offer["proof"] = {
        "type":      "secp256k1-sha256",
        "created":   _now(),
        "signature": sign_document(offer, private_key),
    }
    SIGNED_OFFERS[offer_id] = offer
    return offer


def verify_signed_offer(signed_offer: dict) -> dict:
    """
    Verify a signed offer received from a seller agent.

    Called by the buyer agent or chat interface before presenting the offer
    to the human buyer. This is the runtime enforcement gate.

    Checks:
      1. Offer signature is valid (seller agent signed this document)
      2. Linked manifest exists and its signature is valid (human operator signed)
      3. SKU is authorized in the manifest
      4. Price is within manifest bounds
      5. Discount does not exceed manifest limit

    Returns decision: "accept" or "reject" with reason.
    """
    offer_id = signed_offer.get("offer_id", "unknown")

    proof      = signed_offer.get("proof", {})
    offer_sig  = proof.get("signature")
    offer_pub  = signed_offer.get("public_key_hex")

    if not offer_sig or not offer_pub:
        return {"decision": "reject", "reason": "Signed offer missing proof or public key", "offer_id": offer_id}

    offer_for_verification = {k: v for k, v in signed_offer.items() if k != "seller_manifest"}
    if not verify_signature(offer_for_verification, offer_sig, offer_pub):
        return {"decision": "reject", "reason": "Offer signature invalid", "offer_id": offer_id}

    manifest_id = signed_offer.get("manifest_id")
    manifest    = signed_offer.get("seller_manifest") or SELLER_MANIFESTS.get(manifest_id)
    if not manifest:
        return {"decision": "reject", "reason": f"Seller Manifest {manifest_id} not found", "offer_id": offer_id}

    manifest_proof = manifest.get("proof", {})
    manifest_sig   = manifest_proof.get("signature")
    manifest_pub   = manifest.get("public_key_hex")

    if not manifest_sig or not manifest_pub:
        return {"decision": "reject", "reason": "Seller Manifest missing proof", "offer_id": offer_id}

    if not verify_signature(manifest, manifest_sig, manifest_pub):
        return {"decision": "reject", "reason": "Seller Manifest signature invalid", "offer_id": offer_id}

    sku      = signed_offer.get("sku", "")
    price    = signed_offer.get("unit_price", 0)
    discount = signed_offer.get("discount_pct", 0)

    sku_rule = next((s for s in manifest["authorized_skus"] if s["sku"] == sku), None)
    if not sku_rule:
        return {"decision": "reject", "reason": f"SKU {sku} not authorized in manifest", "offer_id": offer_id}

    if price < sku_rule["min_price_usd"]:
        return {"decision": "reject", "reason": f"Price ${price:.2f} below manifest minimum ${sku_rule['min_price_usd']:.2f}", "offer_id": offer_id}
    if price > sku_rule["max_price_usd"]:
        return {"decision": "reject", "reason": f"Price ${price:.2f} above manifest maximum ${sku_rule['max_price_usd']:.2f}", "offer_id": offer_id}
    if discount > sku_rule["max_discount_pct"]:
        return {"decision": "reject", "reason": f"Discount {discount:.1f}% exceeds manifest limit {sku_rule['max_discount_pct']:.1f}%", "offer_id": offer_id}

    return {
        "decision":       "accept",
        "offer_id":       offer_id,
        "manifest_id":    manifest_id,
        "operator_id":    manifest.get("operator_id"),
        "seller_dnsid":   manifest.get("seller_dnsid"),
        "sku":            sku,
        "unit_price":     price,
        "discount_pct":   discount,
        "total_usd":      signed_offer.get("total_usd"),
        "offer_verified":    True,
        "manifest_verified": True,
    }


def get_seller_manifest(manifest_id: str) -> dict:
    """Retrieve a stored Seller Authorization Manifest by ID."""
    m = SELLER_MANIFESTS.get(manifest_id)
    if not m:
        return {"error": f"Seller Manifest {manifest_id} not found"}
    return dict(m)
