"""
AP2 v0.2.0 Signed Mandates -- Phase 9

AP2 v0.2.0 introduces two mandate types with cryptographic signatures:

  Intent Mandate:
    Created by the human operator (CFO, procurement manager) before the
    procurement run. Expresses top-level spending policy. Signed by the
    human's private key -- in production this is a LoginID biometric
    ceremony (Touch ID / hardware key). The signature proves a specific
    human authorized this policy at a specific moment.

  Cart Mandate:
    Generated by the buyer agent for a specific transaction. Constrained
    by and linked to an Intent Mandate. Signed by the agent's private key.
    The seller receives the Cart Mandate and can verify the full chain:
    agent signed this transaction, the transaction is within policy,
    and the policy was authorized by a verified human.

CHAIN OF TRUST:
  Human biometric (LoginID) --> signs Intent Mandate
  Intent Mandate             --> constrains Cart Mandate
  Agent key (Phase 7)        --> signs Cart Mandate
  Seller                     --> verifies Cart Mandate + Intent Mandate chain

WHY THIS MATTERS (Clerk's Approvals question):
  Phase 4 mandates are policy records but unsigned -- any process can create
  or modify them in memory. AP2 v0.2.0 mandates are cryptographically bound:
  a seller can verify without trusting the buyer's infrastructure.
"""

import uuid
from datetime import datetime, timezone
from typing import Optional

from src.identity.keys import sign_document, verify_signature, public_key_to_hex

INTENT_MANDATES: dict[str, dict] = {}
CART_MANDATES:   dict[str, dict] = {}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def create_intent_mandate(
    operator_id:      str,
    buyer_agent_id:   str,
    approved_sellers: list[str],
    max_per_tx_usd:   float,
    max_total_usd:    float,
    private_key,
    buyer_dnsid:      Optional[str] = None,
) -> dict:
    """
    AP2 v0.2.0: Create a signed Intent Mandate.

    In production, private_key is held by a LoginID-managed hardware credential.
    The signing ceremony is a biometric gesture (Touch ID / Face ID / hardware key).
    The signed mandate becomes a legally defensible artifact: this human authorized
    this spending policy at this timestamp.

    Returns the full mandate dict including signature in the proof field.
    """
    mandate_id = str(uuid.uuid4())
    mandate = {
        "schema":           "ap2:intent-mandate:v0.2.0",
        "mandate_id":       mandate_id,
        "operator_id":      operator_id,
        "buyer_agent_id":   buyer_agent_id,
        "buyer_dnsid":      buyer_dnsid,
        "approved_sellers": approved_sellers,
        "max_per_tx_usd":   max_per_tx_usd,
        "max_total_usd":    max_total_usd,
        "created_at":       _now(),
        "public_key_hex":   public_key_to_hex(private_key.public_key()),
    }
    mandate["proof"] = {
        "type":      "secp256k1-sha256",
        "created":   _now(),
        "signature": sign_document(mandate, private_key),
    }
    INTENT_MANDATES[mandate_id] = mandate
    return mandate


def create_cart_mandate(
    intent_mandate_id: str,
    seller_id:         str,
    amount_usd:        float,
    order_lines:       list[dict],
    private_key,
    buyer_dnsid:       Optional[str] = None,
) -> dict:
    """
    AP2 v0.2.0: Create a signed Cart Mandate for a specific transaction.

    The Cart Mandate is constrained by the Intent Mandate: seller must be
    approved, amount must be within per-tx and total limits. If constraints
    are violated, returns an error dict instead of a mandate.

    In production, private_key is the buyer agent's secp256k1 key from Phase 7.

    Returns the full Cart Mandate dict including proof field, or an error dict.
    """
    intent = INTENT_MANDATES.get(intent_mandate_id)
    if not intent:
        return {"error": f"Intent Mandate {intent_mandate_id} not found"}

    if seller_id not in intent["approved_sellers"] and "*" not in intent["approved_sellers"]:
        return {"error": f"Seller {seller_id} not in Intent Mandate approved list"}
    if amount_usd > intent["max_per_tx_usd"]:
        return {"error": f"Amount ${amount_usd:.2f} exceeds Intent Mandate per-tx limit ${intent['max_per_tx_usd']:.2f}"}

    cart_id = str(uuid.uuid4())
    cart = {
        "schema":             "ap2:cart-mandate:v0.2.0",
        "cart_mandate_id":    cart_id,
        "intent_mandate_id":  intent_mandate_id,
        "seller_id":          seller_id,
        "amount_usd":         amount_usd,
        "order_lines":        order_lines,
        "buyer_dnsid":        buyer_dnsid,
        "created_at":         _now(),
        "public_key_hex":     public_key_to_hex(private_key.public_key()),
    }
    cart["proof"] = {
        "type":      "secp256k1-sha256",
        "created":   _now(),
        "signature": sign_document(cart, private_key),
    }
    CART_MANDATES[cart_id] = cart
    return cart


def verify_cart_mandate(cart_mandate: dict) -> dict:
    """
    AP2 v0.2.0: Verify a Cart Mandate received from a buyer agent.

    Checks:
      1. Cart Mandate signature is valid (agent signed this document)
      2. Linked Intent Mandate exists and its signature is valid (human signed the policy)
      3. Cart amount is within Intent Mandate per-tx limit
      4. Seller is in the Intent Mandate approved list

    Returns a verification result dict with decision: "accept" or "reject".
    Called by the seller before processing any purchase.
    """
    cart_id = cart_mandate.get("cart_mandate_id", "unknown")

    proof = cart_mandate.get("proof", {})
    cart_sig    = proof.get("signature")
    cart_pubkey = cart_mandate.get("public_key_hex")

    if not cart_sig or not cart_pubkey:
        return {"decision": "reject", "reason": "Cart Mandate missing proof or public key", "cart_mandate_id": cart_id}

    if not verify_signature(cart_mandate, cart_sig, cart_pubkey):
        return {"decision": "reject", "reason": "Cart Mandate signature invalid", "cart_mandate_id": cart_id}

    intent_id = cart_mandate.get("intent_mandate_id")
    intent    = INTENT_MANDATES.get(intent_id)
    if not intent:
        return {"decision": "reject", "reason": f"Intent Mandate {intent_id} not found", "cart_mandate_id": cart_id}

    intent_proof  = intent.get("proof", {})
    intent_sig    = intent_proof.get("signature")
    intent_pubkey = intent.get("public_key_hex")

    if not intent_sig or not intent_pubkey:
        return {"decision": "reject", "reason": "Intent Mandate missing proof", "cart_mandate_id": cart_id}

    if not verify_signature(intent, intent_sig, intent_pubkey):
        return {"decision": "reject", "reason": "Intent Mandate signature invalid", "cart_mandate_id": cart_id}

    seller_id  = cart_mandate.get("seller_id")
    amount_usd = cart_mandate.get("amount_usd", 0)

    if seller_id not in intent["approved_sellers"] and "*" not in intent["approved_sellers"]:
        return {"decision": "reject", "reason": f"Seller {seller_id} not in Intent Mandate approved list", "cart_mandate_id": cart_id}

    if amount_usd > intent["max_per_tx_usd"]:
        return {
            "decision": "reject",
            "reason":   f"Amount ${amount_usd:.2f} exceeds Intent Mandate per-tx limit ${intent['max_per_tx_usd']:.2f}",
            "cart_mandate_id": cart_id,
        }

    return {
        "decision":           "accept",
        "cart_mandate_id":    cart_id,
        "intent_mandate_id":  intent_id,
        "operator_id":        intent.get("operator_id"),
        "buyer_dnsid":        cart_mandate.get("buyer_dnsid"),
        "seller_id":          seller_id,
        "amount_usd":         amount_usd,
        "intent_verified":    True,
        "cart_verified":      True,
    }


def get_intent_mandate(mandate_id: str) -> dict:
    """Retrieve a stored Intent Mandate by ID."""
    m = INTENT_MANDATES.get(mandate_id)
    if not m:
        return {"error": f"Intent Mandate {mandate_id} not found"}
    return dict(m)


def get_cart_mandate(cart_id: str) -> dict:
    """Retrieve a stored Cart Mandate by ID."""
    c = CART_MANDATES.get(cart_id)
    if not c:
        return {"error": f"Cart Mandate {cart_id} not found"}
    return dict(c)
